# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ğŸ°åç¾¿'BlogğŸ‘»
subtitle: 'åç¾¿åšå®¢'
description: ''
keywords:
author: åç¾¿'Blog
language: zh-CN
timezone: ''

# URL æ°¸ä¹…é“¾æ¥
url: https://www.houyi.us.ci      #è¯·åœ¨æ­¤å¤„è®¾ç½®æ‚¨çš„ç½‘ç«™ç½‘å€ã€‚ä¾‹å¦‚ï¼Œå¦‚æœæ‚¨ä½¿ç”¨ GitHub Pagesï¼Œè¯·å°†ç½‘å€è®¾ç½®ä¸ºâ€œhttps://username.github.io/projectâ€ã€‚
permalink: posts/:abbrlink/  #æ–‡ç« ç»“å°¾ä¸å¸¦ .html
permalink_defaults:
pretty_urls:
  trailing_index: false # è®¾ç½®ä¸ºfalseå¯ä»æ°¸ä¹…é“¾æ¥ä¸­åˆ é™¤å°¾éšçš„â€œindex.htmlâ€
  trailing_html: false # è®¾ç½®ä¸ºfalseå¯ä»æ°¸ä¹…é“¾æ¥ä¸­åˆ é™¤å°¾éšçš„â€œ.htmlâ€

# ç›®å½•
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# å†™ä½œ
new_post_name: :title.md # æ–°å¸–å­çš„æ–‡ä»¶å
default_layout: post
titlecase: false # å°†æ ‡é¢˜è½¬æ¢ä¸ºé¦–å­—æ¯å¤§å†™æ ¼å¼
external_link:
  enable: true # åœ¨æ–°æ ‡ç­¾é¡µä¸­æ‰“å¼€å¤–éƒ¨é“¾æ¥ falseä¸ºå…³é—­
  field: site # é€‚ç”¨äºæ•´ä¸ªç½‘ç«™
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js  #å½“å‰ä½¿ç”¨çš„ä»£ç é«˜äº®æ¸²æŸ“å¼•æ“

highlight:
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# é¦–é¡µè®¾ç½®
# pathï¼šåšå®¢é¦–é¡µçš„æ ¹è·¯å¾„ã€‚ï¼ˆé»˜è®¤å€¼ï¼šç©ºå­—ç¬¦ä¸²ï¼‰
# per_pageï¼šæ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°é‡ã€‚ï¼ˆ0 = å…³é—­åˆ†é¡µï¼‰
# order_byï¼šæ–‡ç« æ’åºæ–¹å¼ã€‚ï¼ˆé»˜è®¤æŒ‰æ—¥æœŸé™åºæ’åˆ—ï¼‰
# index_generator:
#   path: ''
#   per_page: 10
#   order_by: -date

# ç±»åˆ«å’Œæ ‡ç­¾
default_category: uncategorized
category_map:
tag_map:

# å…ƒæ•°æ®å…ƒç´ 
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# æ—¥æœŸ/æ—¶é—´æ ¼å¼
## Hexo ä½¿ç”¨ Moment.js è§£æå’Œæ˜¾ç¤ºæ—¥æœŸ
## æ‚¨å¯ä»¥è‡ªå®šä¹‰æ—¥æœŸæ ¼å¼ï¼Œå…·ä½“å®šä¹‰è¯·å‚è§æ­¤å¤„ã€‚
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# åˆ†é¡µ
## å°† per_page è®¾ç½®ä¸º 0 å¯ç¦ç”¨åˆ†é¡µ
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# ä¸»é¢˜
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: anzhiyu

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

# å¤–é“¾è·³è½¬æ’ä»¶é…ç½®

# hexo-safegoå®‰å…¨è·³è½¬æ’ä»¶
# see https://blog.liushen.fun/posts/1dfd1f41/
hexo_safego:
  # åŸºæœ¬åŠŸèƒ½è®¾ç½®
  general:
    enable: true                # å¯ç”¨æ’ä»¶
    enable_base64_encode: true  # ä½¿ç”¨ Base64 ç¼–ç 
    enable_target_blank: true   # æ‰“å¼€æ–°çª—å£
  # å®‰å…¨è®¾ç½®
  security:
    url_param_name: 'h'         # URL å‚æ•°å
    html_file_name: 'go.html'   # é‡å®šå‘é¡µé¢çš„æ–‡ä»¶å
    ignore_attrs:               # å¿½ç•¥å¤„ç†çš„ HTML å±æ€§
      - 'data-fancybox'
  # å®¹å™¨ä¸é¡µé¢è®¾ç½®
  scope:
    apply_containers:           # åº”ç”¨çš„å®¹å™¨é€‰æ‹©å™¨
      - '#article-container'
    apply_pages:                # åº”ç”¨çš„é¡µé¢è·¯å¾„
      - "/"
    exclude_pages:              # æ’é™¤çš„é¡µé¢è·¯å¾„

  # åŸŸåç™½åå•
  whitelist:
    domain_whitelist:           # å…è®¸çš„ç™½åå•åŸŸå
      - "houyi.us.ci"
      - "localhost:4000"        
  # é¡µé¢å¤–è§‚è®¾ç½®
  appearance:
    avatar: https://fastly.jsdelivr.net/gh/willow-god/hexo-safego@latest/lib/avatar.png    # å¤´åƒè·¯å¾„
    title: "åç¾¿'Blog"            # é¡µé¢æ ‡é¢˜
    subtitle: "å®‰å…¨ä¸­å¿ƒ"         # é¡µé¢å‰¯æ ‡é¢˜
    darkmode: auto              # æ˜¯å¦å¯ç”¨æ·±è‰²æ¨¡å¼ æ˜¯å¦å¯ç”¨å¤œé—´æ¨¡å¼ï¼Œå¯é€‰autoï¼Œå¯ä»¥è‡ªåŠ¨åˆ‡æ¢äº®æš—æ¨¡å¼ï¼Œtrueé”å®šæš—è‰²æ¨¡å¼ã€‚
    countdowntime: 10           # å€’è®¡æ—¶ç§’æ•°
  # è°ƒè¯•è®¾ç½®
  debug:
    enable: false               # å¯ç”¨è°ƒè¯•æ¨¡å¼

# å›ºå®šé“¾æ¥é…ç½®

# ä¸€ä¸ª Hexo æ’ä»¶ï¼Œç”¨äºæ ¹æ®å¸–å­æ­£é¢çš„æ ‡é¢˜å’Œæ•°æ®ç”Ÿæˆé™æ€å¸–å­é“¾æ¥ã€‚
# https://github.com/rozbo/hexo-abbrlink
# abbrlink config
abbrlink:
  alg: crc32 # æ”¯æŒ CRC16ï¼ˆé»˜è®¤ï¼‰å’Œ CRC32
  rep: hex #æ”¯æŒåè¿›åˆ¶ï¼ˆé»˜è®¤ï¼‰å’Œåå…­è¿›åˆ¶
  drafts: false #(true)å¤„ç†è‰ç¨¿ï¼Œ(false)ä¸å¤„ç†è‰ç¨¿ã€‚falseï¼ˆé»˜è®¤å€¼ï¼‰
  # ä»ç›®å½•æ ‘ç”Ÿæˆç±»åˆ«
  # æ·±åº¦ï¼šè¦ç”Ÿæˆçš„ç›®å½•æ ‘çš„æœ€å¤§æ·±åº¦åº”å¤§äº0
  auto_category:
    enable: true #true(é»˜è®¤å€¼)
    depth: #3(é»˜è®¤å€¼)
    over_write: false
  auto_title: false #å¯ç”¨è‡ªåŠ¨æ ‡é¢˜ï¼Œå¯ä»¥æŒ‰è·¯å¾„è‡ªåŠ¨å¡«å……æ ‡é¢˜
  auto_date: false #å¯ç”¨è‡ªåŠ¨æ—¥æœŸï¼Œå®ƒå¯ä»¥è‡ªåŠ¨å¡«å†™æ—¥æœŸçš„æ—¶é—´ä»Šå¤©
  force: false #å¯ç”¨å¼ºåˆ¶æ¨¡å¼ï¼Œåœ¨è¿™ç§æ¨¡å¼ä¸‹ï¼Œæ’ä»¶å°†å¿½ç•¥ç¼“å­˜ï¼Œå¹¶ä¸ºæ¯ä¸ªå¸–å­è®¡ç®—abbrlinkï¼Œå³ä½¿å®ƒå·²ç»æœ‰äº†abbrlinkã€‚

  # å›ºå®šé“¾æ¥é…ç½®ç»“æŸ
<<<<<<< HEAD

  # ç•™è¨€æ¿

  #envelope_comment
#seehttps://akilar.top/posts/e2d3c450/
envelope_comment:
  enable: true #æ§åˆ¶å¼€å…³
  custom_pic:
    cover: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/violet.jpg #ä¿¡ç¬ºå¤´éƒ¨å›¾ç‰‡
    line: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/line.png #ä¿¡ç¬ºåº•éƒ¨å›¾ç‰‡
    beforeimg: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/before.png # ä¿¡å°å‰åŠéƒ¨åˆ†
    afterimg: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/after.png # ä¿¡å°ååŠéƒ¨åˆ†
  message: #ä¿¡ç¬ºæ­£æ–‡ï¼Œå¤šè¡Œæ–‡æœ¬ï¼Œå†™æ³•å¦‚ä¸‹
    - æœ‰ä»€ä¹ˆæƒ³é—®çš„ï¼Ÿ
    - æœ‰ä»€ä¹ˆæƒ³è¯´çš„ï¼Ÿ
    - æœ‰ä»€ä¹ˆæƒ³åæ§½çš„ï¼Ÿ
    - å“ªæ€•æ˜¯æœ‰ä»€ä¹ˆæƒ³åƒçš„ï¼Œéƒ½å¯ä»¥å‘Šè¯‰æˆ‘å“¦~
  bottom: è‡ªåŠ¨ä¹¦è®°äººå¶ç«­è¯šä¸ºæ‚¨æœåŠ¡ï¼ #ä»…æ”¯æŒå•è¡Œæ–‡æœ¬
  height: #1024pxï¼Œä¿¡å°åˆ’å‡ºçš„é«˜åº¦
  path: #ã€å¯é€‰ã€‘comments çš„è·¯å¾„åç§°ã€‚é»˜è®¤ä¸º commentsï¼Œç”Ÿæˆçš„é¡µé¢ä¸º comments/index.html
  front_matter: #ã€å¯é€‰ã€‘commentsé¡µé¢çš„ front_matter é…ç½®
    title: ç•™è¨€æ¿
    comments: true
    aside: false
    top_img: false
    type: envelope
# ç•™è¨€æ¿ç»“æŸ 

# éŸ³ä¹é¦†
# APlayer
# https://github.com/MoePlayer/hexo-tag-aplayer/blob/master/docs/README-zh_cn.md
aplayer:
  meting: true
  asset_inject: false
# éŸ³ä¹é¦†ç»“æŸ 
=======
>>>>>>> 70a733a0edd4456d4636835b5c4f0d4f7ea9da02
